
select

CODE, FROM_LOC_ID, TO_LOC_ID, OWNER_ID, SKU_ID, CONFIG_ID, TAG_ID, CONDITION_ID, LIST_ID, DSTAMP, REFERENCE_ID, LINE_ID, STATION_ID, USER_ID, UPDATE_QTY, ORIGINAL_QTY, NOTES

from V_INVENTORY_TRANSACTION_ARC ita
where ita.SKU_ID = :SKU
UNION
select

CODE, FROM_LOC_ID, TO_LOC_ID, OWNER_ID, SKU_ID, CONFIG_ID, TAG_ID, CONDITION_ID, LIST_ID, DSTAMP, REFERENCE_ID, LINE_ID, STATION_ID, USER_ID, UPDATE_QTY, ORIGINAL_QTY, NOTES

from V_INVENTORY_TRANSACTION it
where it.SKU_ID = :SKU

order by DSTAMP
