select * from
(
    select LOCATION_ID, ZONE_1, SUBZONE_1, SUBZONE_2, CURRENT_VOLUME, HEIGHT, DEPTH, WIDTH, WEIGHT 
    from V_location
    where SUBZONE_2 = :SUBZONE2
    and SUBZONE_1 = :SUBZONE1
) loc
LEFT JOIN
(
    select TAG_ID, CLIENT_ID, SKU_ID, PALLET_CONFIG, LOCATION_ID, QTY_ON_HAND, QTY_ALLOCATED, CONDITION_ID from V_INVENTORY
) inv
on loc.LOCATION_ID = inv.LOCATION_ID
order by inv.PALLET_CONFIG