SELECT 
LOCATION_ID,
TAG_ID,
SKU_ID,
DESCRIPTION,
QTY_ON_HAND,
QTY_ALLOCATED,
USER_DEF_TYPE_2

FROM V_INVENTORY I
WHERE I.CLIENT_ID = 'NLNEDAP'
AND I.USER_DEF_TYPE_2 <> i.SKU_id
and I.LOCATION_ID like '1%'

order by I.LOCATION_ID
