select 
to_char(AUDIT_DSTAMP,'YYYY/MM/DD HH24:MI:SS') AUDIT_DATE,
AUDIT_USER_ID,
DECODE(AUDIT_ACTION,'U','Update','A','Add','D','Delete') ACTION,
Audit_SESSION_ACTION Sessionaction,
CLIENT_ID,
ALLOCATION_GROUP ALLOC_GRP,
PUTAWAY_GROUP PUT_GRP,
EACH_WIDTH,
EACH_DEPTH,
EACH_HEIGHT,
EACH_WEIGHT,
EACH_VOLUME,
SERIAL_AT_RECEIPT SN_RECEIPT,
SERIAL_AT_PICK SN_PICK,
SERIAL_FORMAT,
USER_DEF_TYPE_7
LAST_UPDATED_BY,
to_char(LAST_UPDATE_DATE,'YYYY/MM/DD HH24:MI;SS') Last_update
from V_SKU_ADT where SKU_ID = '&SKU'
order by audit_dstamp desc